---

- name: Ensure required packages are installed
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to the docker group (optional)
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: yes
  when: username != 'root'

- name: Ensure Docker is installed and running
  ansible.builtin.command:
    cmd: docker --version
  register: docker_version

- name: Display Docker version
  ansible.builtin.debug:
    msg: "Docker version installed: {{ docker_version.stdout }}"