---
- name: Create project directory
  ansible.builtin.file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0755'

- name: Apply docker compose file from template
  become: true
  become_user: "{{ user_name }}"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ wordpress_base_dir }}/docker-compose.yml"
    mode: '0755'

- name: Start WordPress and MySQL with Docker Compose
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: "{{ project_dir }}"

 - name: Ensure WordPress is running
  ansible.builtin.command:
    cmd: docker ps
  register: docker_ps_output

- name: Display Docker containers running
  ansible.builtin.debug:
    msg: "{{ docker_ps_output.stdout }}"